# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
#load CSV
weather_data_load = "../output_data/cities.csv"

#create dataframe
weather_df = pd.read_csv(weather_data_load)

weather_df.head()

weather_df.dtypes

City            object
Country         object
Latitude       float64
Temperature    float64
Longitude      float64
Humidity       float64
Cloudiness     float64
Wind Speed     float64
dtype: object

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#configure gmaps
gmaps.configure(api_key=g_key)

#store latitude and longitudue
location = weather_df[["Latitude","Longitude"]]



#store humidity as weights
humidity = weather_df[["Humidity"]]

max_humid = humidity.max()

humidity = humidity.astype(float)

humidity.head()

   Humidity
0      89.0
1      56.0
2      51.0
3      63.0
4      60.0

In [4]:
#create map

fig = gmaps.figure()

#create heatmap layer
heat_layer = gmaps.heatmap_layer(location,weights=humidity)

#combine layer with map
fig.add_layer(heat_layer)


#print
fig

TraitError: Humidity is not a valid weight. Weights must be floats

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
#narrow city with criteria: max temp between 70 & 80 degrees, wind speed less than 10 MPH, and cloudiness = 0
narrow_city_df = weather_df.loc[(weather_df["Cloudiness"] == 0) & (weather_df["Wind Speed"]<=10) & 
                                (weather_df["Temperature"]>= 70) &(weather_df["Temperature"]<=80)]
#drop null values
narrow_city_df.dropna()

#reset index
narrow_city_df.reset_index(inplace=True)
del narrow_city_df['index']

narrow_city_df

,City,Country,Latitude,Temperature,Longitude,Humidity,Cloudiness,Wind Speed
0,Maltahöhe,NaN,-24.8333,72.28,16.9833,60.0,0.0,4.47
1,São Miguel do Araguaia,BR,-13.2750,71.58,-50.1628,97.0,0.0,4.45
2,New Norfolk,AU,-42.7826,70.00,147.0587,43.0,0.0,1.99
3,Chancay,PE,-11.5714,77.00,-77.2672,83.0,0.0,9.22
4,Arraial do Cabo,BR,-22.9661,74.16,-42.0278,85.0,0.0,5.88
5,East London,ZA,-33.0153,70.70,27.9116,85.0,0.0,2.51
6,Saint-Philippe,RE,-21.3585,78.80,55.7679,57.0,0.0,6.91
7,Saint-Pierre,RE,-21.3393,78.80,55.4781,57.0,0.0,6.91
8,Yenangyaung,MM,20.4667,71.26,94.8833,39.0,0.0,6.35
9,Ouagadougou,BF,12.3642,73.40,-1.5383,25.0,0.0,3.44
10,Ayorou,NE,14.7308,73.36,0.9174,17.0,0.0,9.44
11,Sidrolândia,BR,-20.9319,77.00,-54.9614,61.0,0.0,8.05
12,Manjacaze,MZ,-24.7117,73.80,33.8828,95.0,0.0,3.38
13,Ranong,TH,9.9658,78.80,98.6348,94.0,0.0,4.81
14,Maceió,BR,-9.6658,75.20,-35.7353,94.0,0.0,4.61

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
#create hotel data frame
hotel_df = narrow_city_df.loc[:,["City","Country","Latitude","Longitude"]]


#add hotel name column
hotel_df["Hotel Name"]= ""

hotel_df

                      City Country  Latitude  Longitude Hotel Name
0                Maltahöhe     NaN  -24.8333    16.9833
1   São Miguel do Araguaia      BR  -13.2750   -50.1628
2              New Norfolk      AU  -42.7826   147.0587
3                  Chancay      PE  -11.5714   -77.2672
4          Arraial do Cabo      BR  -22.9661   -42.0278
5              East London      ZA  -33.0153    27.9116
6           Saint-Philippe      RE  -21.3585    55.7679
7             Saint-Pierre      RE  -21.3393    55.4781
8              Yenangyaung      MM   20.4667    94.8833
9              Ouagadougou      BF   12.3642    -1.5383
10                  Ayorou      NE   14.7308     0.9174
11             Sidrolândia      BR  -20.9319   -54.9614
12               Manjacaze      MZ  -24.7117    33.8828
13                  Ranong      TH    9.9658    98.6348
14                  Maceió      BR   -9.6658   -35.7353

In [11]:
#set base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

#set parameters
params = {"type":"hotel",
         "keyword": "hotel",
         "radius": 5000,
         "key": g_key}

In [16]:
#run for loop
for index, row in hotel_df.iterrows():
    latitude = row["Latitude"]
    longitude = row["Longitude"]
    city_name = row["City"]
    
    #keyword to params dictionary
    params["location"]=f"{latitude},{longitude}"
    
    #combine url for API
    print(f"Retrieving Results for Index {index}:{city_name}.")
    response = requests.get(base_url,params=params).json()
    
    #get results
    results = response['results']
    
    #store hotel results in data frame
    try:
        print(f"Closest hotel in {city_name} is {results[0]['name']}.")
        hotel_df.loc[index,'Hotel Name'] = results[0]['name']
        
    except(KeyError, IndexError):
            print("Missing Field...skipping")

print("Done with Search")

Retrieving Results for Index 0:Maltahöhe.
Closest hotel in Maltahöhe is Hotel Hoodia Desert Lodge.
Retrieving Results for Index 1:São Miguel do Araguaia.
Closest hotel in São Miguel do Araguaia is Hotel Veredas do Araguaia.
Retrieving Results for Index 2:New Norfolk.
Missing Field...skipping
Retrieving Results for Index 3:Chancay.
Closest hotel in Chancay is Hotel "EL REY".
Retrieving Results for Index 4:Arraial do Cabo.
Closest hotel in Arraial do Cabo is Orlanova Boutique Hotel.
Retrieving Results for Index 5:East London.
Closest hotel in East London is Blue Lagoon Hotel.
Retrieving Results for Index 6:Saint-Philippe.
Closest hotel in Saint-Philippe is Les Embruns Du Baril.
Retrieving Results for Index 7:Saint-Pierre.
Closest hotel in Saint-Pierre is LODGE PALMAE.
Retrieving Results for Index 8:Yenangyaung.
Closest hotel in Yenangyaung is Lei Thar Gone Guest House.
Retrieving Results for Index 9:Ouagadougou.
Closest hotel in Ouagadougou is Sopatel Silmande Hôtel.
Retrieving Results for Index 10:Ayorou.
Closest hotel in Ayorou is Hotel Amenokal.
Retrieving Results for Index 11:Sidrolândia.
Closest hotel in Sidrolândia is Hotel konquista Sidrolândia.
Retrieving Results for Index 12:Manjacaze.
Closest hotel in Manjacaze is Hotel Mazino.
Retrieving Results for Index 13:Ranong.
Closest hotel in Ranong is Sook Hotel.
Retrieving Results for Index 14:Maceió.
Closest hotel in Maceió is Jatiúca Hotel & Resort.
Done with Search

In [17]:
hotel_df

,City,Country,Latitude,Longitude,Hotel Name
0,Maltahöhe,NaN,-24.8333,16.9833,Hotel Hoodia Desert Lodge
1,São Miguel do Araguaia,BR,-13.2750,-50.1628,Hotel Veredas do Araguaia
2,New Norfolk,AU,-42.7826,147.0587,
3,Chancay,PE,-11.5714,-77.2672,"Hotel ""EL REY"""
4,Arraial do Cabo,BR,-22.9661,-42.0278,Orlanova Boutique Hotel
5,East London,ZA,-33.0153,27.9116,Blue Lagoon Hotel
6,Saint-Philippe,RE,-21.3585,55.7679,Les Embruns Du Baril
7,Saint-Pierre,RE,-21.3393,55.4781,LODGE PALMAE
8,Yenangyaung,MM,20.4667,94.8833,Lei Thar Gone Guest House
9,Ouagadougou,BF,12.3642,-1.5383,Sopatel Silmande Hôtel
10,Ayorou,NE,14.7308,0.9174,Hotel Amenokal
11,Sidrolândia,BR,-20.9319,-54.9614,Hotel konquista Sidrolândia
12,Manjacaze,MZ,-24.7117,33.8828,Hotel Mazino
13,Ranong,TH,9.9658,98.6348,Sook Hotel
14,Maceió,BR,-9.6658,-35.7353,Jatiúca Hotel & Resort

In [18]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [19]:
#establish markers and layers
markers = gmaps.marker_layer(locations)

#add layer to map
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))